---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
  name: monitoring-grafana
  namespace: kube-system
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3000
  selector:
    name: influxGrafana
---
apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-dns
  namespace: kube-system
spec:
  completions: 1
  activeDeadlineSeconds: 300
  template:
    metadata:
      name: grafana-dns
    spec:
      restartPolicy: Never
      containers:
      - name: grafana-dns
        image: antonosmond/k8s-route53:1
        env:
        - name: SERVICE_NAME
          value: monitoring-grafana
        - name: SERVICE_NAMESPACE
          value: kube-system
        - name: FQDN
          value: grafana.dev.k8s.internal.anto.cloud
