apiVersion: v1
clusters:
- cluster:
    certificate-authority: ssl/ca.pem
    server: https://${MASTER_HOST}
  name: default-cluster
contexts:
- context:
    cluster: default-cluster
    user: default-admin
  name: default-system
current-context: default-system
kind: Config
preferences: {}
users:
- name: default-admin
  user:
    client-certificate: ssl/admin.pem
    client-key: ssl/admin-key.pem
