---
apiVersion: v1
kind: Pod
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  containers:
  - name: jenkins
    image: jenkins:latest
    ports:
    - name: ui
      containerPort: 8080
    - name: comms
      containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    app: jenkins
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: 0.0.0.0/0
spec:
  selector:
    app: jenkins
  ports:
  - name: ui
    port: 80
    targetPort: 8080
  type: LoadBalancer
