---
driver:
    name: vagrant

platforms:
  - name: ubuntu-14.04
    driver_plugin: vagrant
    driver_config:
      box: ubuntu/trusty64

provisioner:
  name: ansible_playbook
  playbook: main.yml
  hosts: localhost

suites:
  - name: default
