---
- name: download consul archive
  get_url:
    url: "{{ consul_url }}"
    dest: /tmp/{{ consul_package_name }}
    checksum: "{{ consul_checksum }}"
  register: download

- name: Extract consul to bin directory
  unarchive: src=/tmp/{{ consul_package_name }} dest={{ consul_path }} copy=no
  when: download.changed
